name: trivia_app
description: Flutter project for Mobile Trivia App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

  # firebase
  firebase_database: ^9.0.9
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
#  cloud_firestore: ^3.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - ./assets/pixelComponents/
    - ./assets/images/
      #   - images/a_dot_ham.jpeg


  fonts:
    - family: Garamond
      fonts:
        - asset: fonts/EBGaramond-VariableFont_wght.ttf
        - asset: fonts/EBGaramond-Italic-VariableFont_wght.ttf
          style: italic
    - family: PixelFont
      fonts:
        - asset: fonts/RetroGaming.ttf


      #   - family: Trajan Pro
      #     fonts:s
      #       - asset: fonts/TrajanPro.ttf
      #       - asset: fonts/TrajanPro_Bold.ttf
      #         weight: 700
