// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-7vid2W7uaMdoB50JgyBZpbKU43VIAE',
    appId: '1:227496191191:web:e88a83a90889a672963c92',
    messagingSenderId: '227496191191',
    projectId: 'trivia-app-37d1b',
    authDomain: 'trivia-app-37d1b.firebaseapp.com',
    storageBucket: 'trivia-app-37d1b.appspot.com',
    measurementId: 'G-NRP7YJWRBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpswLflX70eYbGXpDhuaN9SyDjBCMg6Oo',
    appId: '1:227496191191:android:ef02c4d726393bc0963c92',
    messagingSenderId: '227496191191',
    projectId: 'trivia-app-37d1b',
    storageBucket: 'trivia-app-37d1b.appspot.com',
  );
}
